
#(name, idx, is_accumulative)
selected_ob_metrics = [
    ("rpc packet in", 0 ,True),
    ("rpc packet in bytes",1,True),
    ("rpc packet out", 2 ,True),
    ("rpc packet out bytes",3,True),
    ("rpc deliver fail", 4,True),
    ("rpc net delay", 5,True),
    ("rpc net frame delay", 6,True),
    ("mysql packet in", 7,True),
    ("mysql packet in bytes", 8,True),
    ("mysql packet out", 9,True),
    ("mysql packet out bytes", 10,True),
    ("mysql deliver fail", 11, True),
    # ("request enqueue count", 20,True),
    # ("request dequeue count", 21, True),
    # ("request queue time", 22,True),
    # ("trans commit log sync time", 23,True),
    # ("trans commit log sync count", 24,True),
    # ("trans commit log submit count",25 ,True),
    # ("trans start count", 28,True),
    # ("trans total used time", 29,True),
    # ("trans commit count", 30,True),
    # ("trans commit time", 31,True),
    # ("trans rollback count", 32,True),
    # ("trans timeout count", 34,True),
    # ("trans local trans count", 35,True),
    # ("trans distribute trans count", 36,True),
    # ("trans without participant count",37 ,True),
    # ("memstore limit", 393,False),
    # ("major freeze trigger", 392,False),
    # ("total memstore used", 391,False),
    # ("active memstore used",390 ,False),
    # ("user block cache size",387 ,False),
    # ("index block cache size", 385,False),
    # ("DB time", 361,False),
    # ("blockscaned row count", 226,True),
    # useless
    ("trans system trans count",26,True),
    ("trans user trans count",27,True),
    ("commit log replay count",42,True),
    ("sql update count",73,True),
    ("sql delete count",75,True),
    ("sql other count",77,True),
    ("ps prepare count",79,True),
    ("ps execute count",81,True),
    ("sql inner insert count",95,True),
    ("sql inner update count",99,True),
    ("row cache miss",113,True),
    ("row cache hit",112,True),
    ("memstore write lock succ count",187,True),
    ("memstore write lock fail count",188,True),
    ("DB time",360,True),
    ("DB inner sql time",362,True),
    ("memory usage",396,False),
    ("cpu usage",399,True),
    #
    ("blockscaned data micro block count",225 ,True),
    ("index micro block cache hit", 224,True),
    ("data micro block cache hit",222 ,True),
    ("accessed data micro block count", 221,True),
    ("local trans total used time", 60,True),
    ("distributed trans total used time", 61,True),
    ("sql select count", 67, True),
    ("sql local count", 86, True),
    ("sql remote count", 87, True),
    ("sql distributed count",88 ,True)
]
# selected_ob_metrics = [("sql distributed count",88 ,True)]

